### ISSUE TITLE
tmdb-addon interfering with stremio-tmdb-alternatives

### ISSUE THREAD

**Issue by FallenGuardian** [mrcanelas/tmdb-addon#1]
First things first, a huge thanks for the TMDB Addon. :thumbsup:

The problem I'm having is that I'm using both this addon and stremio-tmdb-alternatives. This gives issues while having it both installed.

1. The first one is that for example if I install stremio-tmdb-alternatives after this addon it won't show the alternative ordering anymore, but it will when I install it after stremio-tmdb-alternatives.
2. When I finish watching and episode and browse the library the player shows up shortly. It probably starts 2 instances because of both addons being installed? And closes the other one when browsing the library.

**Comment by mrcanelas** [comment]
I can use the same idea that TMDB Alternatives used for his addon, but he may not like it because it can look like a copy.
