### ISSUE TITLE
Synopsis in another language

### ISSUE THREAD

**Issue by virtuacool** [mrcanelas/tmdb-addon#10]
Hi! Two situations I would like to leave:

1) When I try to install version v3.0.7, through Stremio, on my android smartphone, a code page appears. But when I install v.3.0.6 this does not happen.

2) I see that I have synopses in Portuguese, in very few movies/TV shows (almost none), but most appear in English.

Something I'm not doing well?

**Comment by jaruba** [comment]
> a code page appears

what does that mean? can you provide a screenshot?

addons that have configuration pages cannot be auto-updated, you need to uninstall the previous version and install again through the configuration page

**Comment by virtuacool** [comment]
![Screenshot_20230102-225552](https://user-images.githubusercontent.com/48911380/210285110-21e5d24a-75e0-48c1-b69a-304a17355bca.png)

**Comment by virtuacool** [comment]
Language example:

This one is in portuguese
![image](https://user-images.githubusercontent.com/48911380/210285879-04a6e10c-ca65-4714-8c95-e6bea7801880.png)

The others are in English (almost all)
![image](https://user-images.githubusercontent.com/48911380/210285902-7cb2aa2d-7c40-4ae4-b343-350483a99035.png)

![image](https://user-images.githubusercontent.com/48911380/210285910-d7d0ae89-4cc7-4cb9-86bb-f65ffb090956.png)

**Comment by mrcanelas** [comment]
Hi, the addon is undergoing some updates, can you test again and see if the error persists?

**Comment by virtuacool** [comment]
Hi! It still persists. I even uninstalled Stremio from my Android smartphone. I downloaded it from the official page and reinstalled Stremio again. Later I uninstalled the TMDB addon and reinstalled. First I select the sprocket, choose the language and install the addon. After installing it, I check in the installed addon that it has the correct language indication. However, it still continues with the information in English! I did all this about an hour ago.

**Comment by virtuacool** [comment]
Something that caught my attention is that in the only movie that the synopsis appears in Portuguese, if you change the language to French, in that same movie the synopsis changes to French. But all the rest are still in English.
![image](https://user-images.githubusercontent.com/48911380/210671687-f0d938ec-1790-4afb-a050-5d892d39f1e6.png)

**Comment by virtuacool** [comment]
I hope my imputs help....
One more strange thing!
1) When I uninstall the TMDB addon I get the "error when obtaining information", however all the others do not give an error, and return in English. I emphasize that it is only in this movie that I get results when I have the TMDB addon installed.
![image](https://user-images.githubusercontent.com/48911380/210749817-e74eca0b-f7b4-4a69-bd85-58bdc2b2c8fe.png)


2) I just installed Stremio on the phone. With the new account he created, and after installing the TMDB addon, and configuring the PT-pt language, all contents are returned in English. But if I enter the movie "The Woman King" with my login, the content returns in Portuguese and the rest in English! That is, on my friend's cell phone, the result is the same when I use my credentials, but when I use his credentials, everything returns in English.

**Comment by virtuacool** [comment]
Hey, today I used Stremio and the synopses were already in Portuguese. I haven't used it in a while, so I don't know what happened. However I appreciate any action you have taken!

![image](https://user-images.githubusercontent.com/48911380/211935304-d19ae168-53ed-4b84-aed8-c65abb6a9e37.png)

![image](https://user-images.githubusercontent.com/48911380/211935325-35b2f43b-5da3-457b-8ca0-de5b9067dba0.png)
