### ISSUE TITLE
I believe the addon may no longer be working with Trakt scrobbling

### ISSUE THREAD

**Issue by Dasnap** [mrcanelas/tmdb-addon#16]
This addon has been my go-to for Stremio for a while, so I assumed my issues with Trakt not scrobbling the past few weeks may have been application-wide. That was until I tried watching some films with a different addon (Trakt.tv addon) and scrobbling worked just fine. I think it may be this addon specifically that no longer works with the Trakt integration.

**Comment by mrcanelas** [comment]
In fact the TMDB Addon doesn't have integration with Trakt, I don't know how the Trakt API works, adding this should be an improvement of the addon, it's not in the scope but when I have some time I can study it.

**Comment by Dasnap** [comment]
I've actually tested some more myself with odd results. I created a completely new Stremio account and the Trakt scrobbling works fine with the addon. I'm assuming Trakt scrobbling isn't opt-in for addons? If Stremio can get it to work then it just does it. It's just odd that I've managed to do something on an account specific level that managed to break scrobbling for one specific addon.
