### ISSUE TITLE
Login to TMDB

### ISSUE THREAD

**Issue by max1c** [mrcanelas/tmdb-addon#17]
Is there a way to login to be able to change the language, see personal lists, turn off filter profanity, and adult items search?

**Comment by max1c** [comment]
No update on this at all? Can you guys please add the TMDB API key support? This would make things so much easier.

**Comment by mrcanelas** [comment]
Request implemented in commit [
2334c89](https://github.com/mrcanelas/tmdb-addon/commit/2334c898ddd10ab56bf117b17c451b106e39c6ee), hope it works fine now.

**Comment by max1c** [comment]
When I try to login with TMDB I get:

**Comment by oleglucic** [comment]
Same thing here. Might be that the dev hasn't implemented the right token. I'm sure it'll be resolved soon.

**Comment by mrcanelas** [comment]
I believe that everything is ok now, the problem was in the beamup servers cache, the request token can only be used once and is valid for 15 minutes, the server sent an expired request token, to install I recommend doing CTRL + F5 to remove your browser cache.

**Comment by Aerya** [comment]
Hi @mrcanelas 

Thanks for the project but I still got "Invalid token" error. On your public instance or self-hosted using your repos. Any idea?


```
Invalid request token

The access token you submitted is invalid. Most of the time, this is because the token has expired. Try creating a new one and make sure you copy it correctly. If you continue to experience problems, contact the developer of the application you are using.
```
