### ISSUE TITLE
I think the addon is broken again 

### ISSUE THREAD

**Issue by nyouness** [mrcanelas/tmdb-addon#19]
The host server takes time to load and again no longer showing search via desktop client.

**Comment by AlexNexuss** [comment]
I confirm that there are some problems with the server. For example, I cannot change the metadata language.
In Stremio I get the error "ERR_OPENING_MEDIA". Only default settings work.
I tried not to click the “install” button, but instead copied the link address, replacing “stremio” with “http”. When I enter this link in the browser, I get a 504 error, and not the contents of the json file.
For example, with Torrentio there is no such problem.

**Comment by mrcanelas** [comment]
Hello, I'm already aware of this problem, unfortunately I don't have a computer, until I can buy another one I won't be able to solve this.
