### ISSUE TITLE
Bug with popular catalog with languages besides en-US

### ISSUE THREAD

**Issue by Arcami** [mrcanelas/tmdb-addon#21]
When installing the addon for any language besides en-US (even en-GB or other English varieties) there's a bug with the "TMDB - Popular" category: the subcategory "Top" won't display anything, only when selecting a specific genre.

Now that [it's possible to place addons above Cinemeta](https://www.reddit.com/r/StremioAddons/comments/1ak8vkt/showcase_stremio_addon_manager_effortlessly/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), I wanted to make TMDB the main catalog, but this bug makes the Discover tab empty unless you manually change the categories every single time (which is very annoying on Android TV).

It would also be nice to change which category shows first, so instead of popular movies appearing first, move another category like "Trending" or "By Language" to the top of the dropdown.

Thank you for all your effort.

**Comment by mrcanelas** [comment]
The bug happened because TMDB changed the way it searches the API, it has already been fixed, but there is a Beamup Server cache, it takes 24 to 48 hours for the caches to expire
