### ISSUE TITLE
[TMDB] notified about new episodes

### ISSUE THREAD

**Issue by vitouchiha** [mrcanelas/tmdb-addon#27]
Is there a way to add the option to get notified about new episodes. Which only appears if you use Cinemeta and not TMDB. This is to be clear

![photo_5974268705686799125_w](https://github.com/user-attachments/assets/5268aee9-4d61-4b64-abda-6219f1b8c3f5)

**Comment by mrcanelas** [comment]
This is an implementation of Stremio itself, not of the addon, there is still no support for third-party addons to provide calendars, I have already asked the Stremio team about the possibility but it is not in the plans.
