### ISSUE TITLE
Custom catalog titles?

### ISSUE THREAD

**Issue by miguelssimao** [mrcanelas/tmdb-addon#28]
First of all, thank you so much for including the option to remove the TMDB prefix from catalogs.

I would like to ask for the ability to change the catalog names with custom input through the configuration page.

Cinemeta also has a `Popular` catalog and I personally don't like having two different catalogs with the same name.

**Comment by mrcanelas** [comment]
Hi, so I don't think this will fall within the scope, there is already the option to add the prefix to differentiate it from Cinemeta.

**Comment by TwilightMercy** [comment]
Hi,
If configuring "Use TMDB prefix in catalogs" to on, where is the change visually located?
Thanks
