### ISSUE TITLE
Missing Posters

### ISSUE THREAD

**Issue by bramdsgn** [mrcanelas/tmdb-addon#29]
Added Items (linked to TMDB add on) to Library have missing Posters, is there a fix ? considering Cinemeta doesn't have this problem

![image](https://github.com/user-attachments/assets/cebc7697-dfff-43ab-8812-d42096e486cf)

**Comment by mrcanelas** [comment]
Have these items been added to the TMDB catalog? Have you removed cinemeta? The TMDB Addon did not yet provide support for IMDBId's, the latest update added this option and it needs to be enabled on the configuration page.

**Comment by bt4ibwem8** [comment]
@mrcanelas 
I think this issue should be reopened. I have same issue. Just posters are missing, when i click on it for details, all metadata seems to be ok (loaded from tmdb website).
Try to add for example the show YOU (2018) if it will be blank also for you.

**Comment by mrcanelas** [comment]
Let me try to explain in a way that is easier to understand, Cinemeta uses ImdbId, TMDB Addon uses TmdbId, if you added something to your library using Cinemeta, Stremio tries to search for the posters in Cinemeta, if you removed Cinemeta the poster will not appear, to provide the metadata for the item TMDB will work, but the item in the library is not updated, it will still be linked to Cinemeta, but to solve it you must search for the movie/series and add it through the TMDB catalog and remove the old one that was added by Cinemeta.

**Comment by oleglucic** [comment]
I think that enabling the IMDBId support option during addon configuration resolves this problem. It did for me.

**Comment by bt4ibwem8** [comment]
I added it through TMDB - popular catalog but still no poster. But before it was added from Cinemeta, i removed it from Library but maybe it was not removed completely...

**Comment by oleglucic** [comment]
If you are on mobile try removing the cache (same applies to TV). If on a desktop try refreshing the app Fn+F5.

**Comment by bt4ibwem8** [comment]
I am on Windows native app, but the same apply also when i try web.stremio.com from Firefox

**Comment by mrcanelas** [comment]
Something that works for me is to play an episode on the item I want to update. Stremio updates the library data when you play something.

**Comment by bt4ibwem8** [comment]
thanks, it helped... what about that "Provide metadata for IMDBId"? Dunno if i should leave it enabled, i see no difference on the details page in comparison when i had it disabled before...

**Comment by mrcanelas** [comment]
This option is used to take translated metadata to other catalogs that use ImdbId, for example Streaming Catalogs, if you only use TMDB this option does not change anything.

**Comment by mrcanelas** [comment]
This option is used to take translated metadata to other catalogs that use ImdbId, for example Streaming Catalogs, if you only use TMDB this option does not change anything.

**Comment by celguar** [comment]
Hello, I have an issue with missing thumbnails and posters (that background on a movie page) when using TMDB + ru language. Cinemeta is there and works fine. Maybe addon tries to load ru images, and there's none? Can we have some sort of fallback to EN images if localized are not found? Just my speculation of course. Really like the addon, but lack of images makes it hard to use
