### ISSUE TITLE
Option to disable catalogs

### ISSUE THREAD

**Issue by G1fan** [mrcanelas/tmdb-addon#30]
It would be great to have the option in the configurator to disable catalogs outright.

My use of the addon is exclusively to supplement Cinemeta when searching for specific content.
The catalogs and discover options only serve to clutter the UI in that use case.

I love the addon. Thanks for all your hard work!
Hoping this isn't outside of the project scope.

**Comment by mrcanelas** [comment]
Unfortunately this is an option that is completely out of scope, most users are looking for an alternative to Cinemata, it doesn't make sense to add another option to the configuration page just for that.
