### ISSUE TITLE
Add the tier 0 for fetching the ratingposterdb in english.

### ISSUE THREAD

**Issue by idan1109** [mrcanelas/tmdb-addon#31]
function getRpdbPoster(type, id, language, rpdbkey) {
  const tier = rpdbkey.split("-")[0]
  const lang = language.split("-")[0]
  if (tier === "t0" || tier === "t1" || lang === "en") {
    return `https://api.ratingposterdb.com/${rpdbkey}/tmdb/poster-default/${type}-${id}.jpg?fallback=true`
  } else {
    return `https://api.ratingposterdb.com/${rpdbkey}/tmdb/poster-default/${type}-${id}.jpg?fallback=true&lang=${lang}`
  }
}

**Comment by mrcanelas** [comment]
According to the RPDB API [documentation](https://rpdb.docs.apiary.io/#introduction/request-limits) there is no tier 0



![image](https://github.com/user-attachments/assets/78c012b4-ecab-4fb3-82df-08641415b467)

**Comment by idan1109** [comment]
hey @mrcanelas thanks for you answer. I think the documentation is not up to date.
https://www.reddit.com/r/StremioAddons/comments/1f12nz9/free_rpdb_is_now_generally_available/
here there a link from the dev which talks about it. I registered to patreon for the free tier an it contains the t0. if you want to check you can do it also. if I select a language with your addon and then add the t0 API key I can't see any poster from rpdb .. at least it should show in it in English!

**Comment by mrcanelas** [comment]
I didn't know that, it was added in the last update

**Comment by idan1109** [comment]
are you going to add it? :)
