### ISSUE TITLE
Fix " Re:ZERO -Starting Life in Another World- "  order

### ISSUE THREAD

**Issue by nyouness** [mrcanelas/tmdb-addon#32]

**Comment by nyouness** [comment]
thank you for the update , but should be season 3 not 4
![Screenshot 2024-10-03 231651](https://github.com/user-attachments/assets/90a18252-e41a-47ac-9775-1a8e80dc2914)

**Comment by mrcanelas** [comment]
How strange here for me it appears as season 3 on stremio for desktop.

![image](https://github.com/user-attachments/assets/0ed3d825-9e76-420b-a127-e900e21ecf93)

**Comment by nyouness** [comment]
it was a bug i reinstalled Stremio and now fine , thank you again for the updates
