### ISSUE TITLE
Announce support for idPrefix "tt", i.e. IMDB IDs

### ISSUE THREAD

**Issue by parski** [mrcanelas/tmdb-addon#33]
This addon appears to support `tt` IDs, i.e. IMDB IDs. However, in the manifest is only announces `tmdb:` IDs under the `idPrefixes` property. Some users [modify their clients](https://www.reddit.com/r/StremioAddons/comments/1d8wbul/how_to_remove_cinemeta/) consuming your addon to swap out your `idPrefixes` so they can use it to resolve IMDB IDs.

I think it would be a good feature to either:

1) Add `tt` to the list of supported `idPrefixes`.

or

2) Add an option to the configuration that will add `tt` to the list of supported `idPrefixes` if selected.

If there are good reasons to not do either of the above options I would be very interested to learn about them also.

**Comment by parski** [comment]
You only dishonor yourself, maintainer. Your source is open but your mind is closed.

**Comment by mrcanelas** [comment]
I want to understand why you said that? Did I not meet your request? Did I make the modification you asked for? Charging anything is very easy, but no one donates a penny to help the dev.

**Comment by mrcanelas** [comment]
I didn't copy your changes, I saw your commit asking for the changes, I did it my way and only later did I see that you had made a PR, I didn't accept your PR because the HTML needed changes due to the page's responsiveness, you'll say I'm lying but I don't owe you an explanation.
