### ISSUE TITLE
Metadata showing on desktop but not on android and android tv

### ISSUE THREAD

**Issue by oleglucic** [mrcanelas/tmdb-addon#35]
I have configured TMDB as my main catalog addon and removed cinemeta. Everything works fine and tmdb synced with my library which was created using cinemeta and could load everything normally, but that is only on stremio web and windows app. When i go on my phone and open some previously saved movie from cinemeta, it just loads stream links and not any metadata, same on the tv. Why did Web and Windows app successfully sync TMDB addon with library and everything works perfectly, but android was unable to do so?
Help would be appreciated 😊

**Comment by mrcanelas** [comment]
From what you told me it seems to be a problem with the Stremio client, there's not much I can do.

**Comment by oleglucic** [comment]
Thank you! I'll be sure to notify them.
