### ISSUE TITLE
Serbian transliteration

### ISSUE THREAD

**Issue by oleglucic** [mrcanelas/tmdb-addon#36]
TMDB offers metadata in serbian cyrillic but people don't use it that often. When searching in stremio, you should add latin support ofr sr-RS aka transliteration so people can find things more easily. If this isn't possible at all, you can at least enable to search in english in sr-RS addon. This would help so many people from the balkans. Thank you : )

**Comment by mrcanelas** [comment]
I think it's possible, I'm a bit short on time right now, but when I have some time I'll look into it for you.

**Comment by oleglucic** [comment]
Thank you so much! Take your time, until then I'll leave this open. You will have the honours of closing this case. In the meantime, I will try to answer as much issues here as I could. Hope this helps you just a little bit : )

**Comment by oleglucic** [comment]
Tested it out a little bit. Works fine but needs some work. When i find the exact errors i'll be sure to contact you.
