### ISSUE TITLE
Receive notifications

### ISSUE THREAD

**Issue by bt4ibwem8** [mrcanelas/tmdb-addon#41]
Should i see "Receive notifications for new episodes" option in Stremio Windows app? I see it in web.stremio.com but in Windows app i see it only for Cinemeta, not for Tmdb addon.

**Comment by mrcanelas** [comment]
Stremio does not support calendar from third party addons only for Cinemeta, @jaruba told me that this will be possible in the future but it is not possible now.

**Comment by oleglucic** [comment]
Stremio doesn't support calendar functions for catalogues besides Cinemeta. Stremio devs have said that they won't implement that feature shortly.

**Comment by bt4ibwem8** [comment]
i see, maybe the are testing it now with the web version of Stremio
