### ISSUE TITLE
Cache not renewing

### ISSUE THREAD

**Issue by oleglucic** [mrcanelas/tmdb-addon#47]
Even though cache settings were changed, catalogues don't refresh on daily basis on android devices. Same applies to metadata, it's always the same until the app cache is cleared. What is going on?

EDIT: Cache refreshes on neither of the platforms (Web, Win, Lin, And)!

**Comment by mrcanelas** [comment]
Actually I didn't look at the PR you made right you only changed the TLL of the mongo cache, you didn't change the http headers cache.
