### ISSUE TITLE
The addon is not working

### ISSUE THREAD

**Issue by Darkxc9** [mrcanelas/tmdb-addon#6]
The addon is no longer working, I removed it and wanted to re-install it, but there seems to be a problem with the site that cannot be reinstalled, and the site page opens after a long time. I tried again, but there is a problem, I do not know what I hope to fix the problem. 

 Thank you greetings

**Comment by mrcanelas** [comment]
How are you? the addon is hosted on the Beamup server, sometimes the server is offline, just wait for it to come back, if it is not appearing in the addons list you can install it through this link: [Configure](https://94c8cb9f702d-tmdb-addon.baby -beamup.club/configure)
